# Generated by Django 4.2.6 on 2023-11-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='post',
            new_name='role',
        ),
    ]
