# Generated by Django 4.2.6 on 2023-11-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_rename_name_director_fio_rename_post_director_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='image',
            new_name='photo',
        ),
    ]
