# Generated by Django 4.2.6 on 2023-11-23 07:40


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='изображение к мероприятию')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo_album_url', models.URLField(verbose_name='ссылка на фото-альбом')),
                ('link_to_media', models.URLField(verbose_name='ссылка на СМИ')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
            },
        ),
    ]
