# Generated by Django 4.2.6 on 2023-11-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='title',
        ),
    ]
