# Generated by Django 4.2.6 on 2023-11-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_rename_name_achievement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='image',
            new_name='photo',
        ),
    ]
