# Generated by Django 4.2.6 on 2023-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение к мероприятию')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('link_to_photo_album', models.URLField(verbose_name='ссылка на фото-фльбом')),
                ('link_to_the_docs', models.URLField(verbose_name='ссылка на документы')),
                ('venue', models.URLField(verbose_name='место проведения')),
                ('application_start_date', models.DateField(verbose_name='дата начала приёма заявок')),
                ('date_of_summing_up', models.DateField(verbose_name='дата подведения итогов')),
                ('organizers_photo', models.ImageField(blank=True, upload_to='organizers_images/%Y/%m/%d', verbose_name='фотография главного организатора')),
                ('organizers_word', models.URLField(verbose_name='слово главного организатора')),
                ('link_to_competition_task', models.URLField(verbose_name='ссылка на конкурсное задание')),
            ],
            options={
                'verbose_name': 'хардатон',
                'verbose_name_plural': 'хардатоны',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение к мероприятию')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('competition_rules', models.TextField(verbose_name='правила соревнования')),
                ('implementation_scale', models.TextField(verbose_name='масштаб реализации')),
                ('hardathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardathon.hardathon', verbose_name='хардатон')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
