# Generated by Django 4.2.6 on 2023-11-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardathon',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='photo',
        ),
    ]
