# Generated by Django 4.2.6 on 2023-10-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0002_hardathon_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardathon',
            old_name='partner',
            new_name='partners',
        ),
    ]
