# Generated by Django 4.2.6 on 2023-11-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0002_rename_link_to_the_docs_hardathon_documents_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardathon',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
