# Generated by Django 4.2.6 on 2024-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0002_alter_hardathon_documents_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardathon',
            name='summing_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата подведения итогов'),
        ),
    ]
