# Generated by Django 4.2.6 on 2023-11-16 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0003_rename_partner_hardathon_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardathon',
            name='application_end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 11, 39, 24, 527684), verbose_name='дата окончания приёма заявок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardathon',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 11, 38, 28, 603942), verbose_name='дата проведения'),
        ),
        migrations.AddField(
            model_name='hardathon',
            name='social_media_mention',
            field=models.URLField(default='http://127.0.0.1', verbose_name='упоминание в сми'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardathon',
            name='link_to_photo_album',
            field=models.URLField(verbose_name='ссылка на фото-альбом'),
        ),
    ]
