# Generated by Django 4.2.6 on 2023-11-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='link_to_the_site',
            new_name='link',
        ),
    ]
