# Generated by Django 4.2.6 on 2023-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_image_partner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='изображение к мероприятию'),
        ),
    ]
