# Generated by Django 4.2.6 on 2023-12-07 15:18

from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_alter_partner_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='изображение к мероприятию')),
                ('title', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo_album_url', models.URLField(verbose_name='ссылка на фото-альбом')),
                ('documents_url', models.URLField(verbose_name='ссылка на документы')),
                ('location', models.URLField(verbose_name='место проведения')),
                ('event_date', models.DateField(verbose_name='дата проведения')),
                ('social_media_mention', models.URLField(verbose_name='упоминание в сми')),
                ('registration_link', models.URLField(verbose_name='ссылка на регистрацию')),
                ('partners', models.ManyToManyField(to='partners.partner', verbose_name='партнёры классического мероприятия')),
            ],
            options={
                'verbose_name': 'классическое мероприятие',
                'verbose_name_plural': 'классические мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searcher_fio', models.CharField(max_length=150, validators=[events.validators.ValidateFullName()], verbose_name='фио участника')),
                ('searcher_bmstu_group', models.CharField(max_length=15, validators=[events.validators.ValidateGroup()], verbose_name='учебная группа')),
                ('participants_count', models.IntegerField(verbose_name='количество людей в команде')),
                ('required_competencies', models.TextField(verbose_name='необходимые компетенции')),
                ('seacher_VK', models.URLField(verbose_name='ссылка на ВКонтакте соискателя')),
                ('additional', models.TextField(verbose_name='дополнительная информация')),
                ('classic_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.classicevent', verbose_name='классическое мероприятие')),
            ],
            options={
                'verbose_name': 'анкета',
                'verbose_name_plural': 'анкеты',
                'ordering': ['-id'],
            },
        ),
    ]
