# Generated by Django 4.2.6 on 2024-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_partner_link'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicevent',
            name='documents_url',
            field=models.URLField(blank=True, verbose_name='ссылка на документы'),
        ),
        migrations.AlterField(
            model_name='classicevent',
            name='partners',
            field=models.ManyToManyField(blank=True, to='partners.partner', verbose_name='партнёры классического мероприятия'),
        ),
        migrations.AlterField(
            model_name='classicevent',
            name='photo_album_url',
            field=models.URLField(blank=True, verbose_name='ссылка на фото-альбом'),
        ),
        migrations.AlterField(
            model_name='classicevent',
            name='social_media_mention',
            field=models.URLField(blank=True, verbose_name='упоминание в сми'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='additional',
            field=models.TextField(blank=True, verbose_name='дополнительная информация'),
        ),
    ]
