# Generated by Django 4.2.6 on 2023-10-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_classicevent_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classicevent',
            old_name='partner',
            new_name='partners',
        ),
    ]
