# Generated by Django 4.2.6 on 2023-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_image_classicevent_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-id'], 'verbose_name': 'анкета', 'verbose_name_plural': 'анкеты'},
        ),
        migrations.AlterField(
            model_name='classicevent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='изображение к мероприятию'),
        ),
    ]
