# Generated by Django 4.2.6 on 2023-12-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_image_classicevent_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classicevent',
            old_name='link_to_photo_album',
            new_name='photo_album_url',
        ),
    ]
