# Generated by Django 4.2.6 on 2023-11-16 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_partner_classicevent_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicevent',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 11, 38, 28, 603942), verbose_name='дата проведения'),
        ),
        migrations.AddField(
            model_name='classicevent',
            name='social_media_mention',
            field=models.URLField(default=datetime.datetime(2023, 11, 16, 11, 38, 49, 102003), verbose_name='упоминание в сми'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classicevent',
            name='link_to_photo_album',
            field=models.URLField(verbose_name='ссылка на фото-альбом'),
        ),
    ]
