# Generated by Django 4.2.6 on 2023-11-25 15:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('link_to_driving_scheme', models.URLField(verbose_name='ссылка на схему проезда')),
                ('link_to_vk', models.URLField(verbose_name='ссылка на вк')),
                ('link_to_telegram', models.URLField(verbose_name='ссылка на телеграм')),
            ],
            options={
                'verbose_name': 'статические данные',
                'verbose_name_plural': 'статические данные',
            },
        ),
    ]
